# service_name  listen_port(https)  target_port(http)
default_ui      443                 80
mjpg_streamer   8080                8443
fluidd          4408                4443
mainsail        4409                5443
