pid = /tmp/rinkhals/tls-addon.pid
cert = /useremain/home/rinkhals/printer_data/certs/moonraker.cert
key = /useremain/home/rinkhals/printer_data/certs/moonraker.key

foreground = no
client = no

[default_ui]
accept = 443
connect = 127.0.0.1:80

[mjpg_streamer]
accept = 8443
connect = 127.0.0.1:8080

[fluidd]
accept = 4408
connect = 127.0.0.1:4443

[mainsail]
accept = 4409
connect = 127.0.0.1:5443
